export {default as Login} from './Login'
export {default as Home} from './Home'
export {default as Header} from './Header'
export {default as User} from './localComponent/User/User'
export {default as Payment} from './localComponent/Payment/Payment'
export {default as CreateNews} from './localComponent/Payment/CreateNews'
export {default as DetailNews} from './localComponent/Payment/DetailNews'
export {default as Post} from './localComponent/Post/Post'
export {default as Product} from './localComponent/Product/Product'
export {default as Other} from './localComponent/Other/Other'
export {default as Setting} from './localComponent/Setting/Setting'
export {default as Profile} from './Profile'
export {default as ButtonCustom} from './Button/Button'
export {default as ProductCard} from './localComponent/Product/ProductCard'
export {default as Footer} from './Footer/Footer'

